name: firmware

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
    - run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi-gcc.cmake
    - run: cmake --build build --target prusa_x_nfc_01_fw
    - uses: softprops/action-gh-release@v2
      with:
        tag_name: fw-${{ github.run_number }}
        files: build/prusa_x_nfc_01_fw.bin
